### ISSUE TITLE
Allow no name when creating plant

### ISSUE THREAD

**Issue by EmmanuelMess** [7LPdWcaW/GrowTracker-Android#108]
I ended up naming some of my plants "Tree 1" "Tree 2" "Tree 3" etc. I am not very good with naming things, and prefer to use the plant strain, garden and photo as identifiers.

**Comment by 7LPdWcaW** [comment]
You can put anything in to the fields. "Name" and "Strain" are more "title" and "description". I personally use the name field for the strain and the strain field for the seed company

**Comment by 9YbQiuEohUu1** [comment]
It would actually be neat if the Name field would autofill with "Plant01," "Plant02" etc. when left empty. This would be handy for people who like to keep track of everything and eliminate the hussle for those who do not care about names at all. More quality of life improvement than an issue, but the one worth considering.
