### ISSUE TITLE
Add way to show complete image

### ISSUE THREAD

**Issue by EmmanuelMess** [7LPdWcaW/GrowTracker-Android#109]
Add way to show complete image of plant in the card. Something like (but without the bottom stars):

![](https://storage.googleapis.com/spec-host-backup/mio-design%2Fassets%2F0B6xUSjjSulxcaVRham4xV1UtbGM%2Fcards-uicontrols-1.png)

**Comment by 7LPdWcaW** [comment]
Closed in c6277f508d26864acc99f2ae35484d69e3a99796

Will only really work for square images. Portrait/landscape images will always be cropped
