### ISSUE TITLE
Add buttons to the card to access photos, history and stadistics directly

### ISSUE THREAD

**Issue by EmmanuelMess** [7LPdWcaW/GrowTracker-Android#110]
Maybe something like this to the bottom right of the plant cards (with gallery, history and chart icons respectively)?:
![](https://storage.googleapis.com/spec-host-backup/mio-design%2Fassets%2F1gK3LAZc8DnoB8Gtepo2ea3oPFr3h0K5I%2Fspecs-toggle-buttons.png)

**Comment by 7LPdWcaW** [comment]
Closed in c6277f508d26864acc99f2ae35484d69e3a99796
