### ISSUE TITLE
Use Glide for efficient preloading of images

### ISSUE THREAD

**Issue by EmmanuelMess** [7LPdWcaW/GrowTracker-Android#119]
Images sometimes flicker or are loaded late, after the item in the list has been shown. I strongly recommend using Glide.

**Comment by 7LPdWcaW** [comment]
Will need research into if these new libraries allow me to create custom loaders to handle encrypted images

**Comment by EmmanuelMess** [comment]
> Will need research into if these new libraries allow me to create custom loaders to handle encrypted images

I have used Glide previously, and [it does](https://bumptech.github.io/glide/tut/custom-modelloader.html).

**Comment by 7LPdWcaW** [comment]
Is the only way to use Glide with configuration to use annotation processors? I think that will be overkill for the amount of image loading that's being done. I have basic knowledge with Picasso so will try that

**Comment by EmmanuelMess** [comment]
> Is the only way to use Glide with configuration to use annotation processors? I think that will be overkill for the amount of image loading that's being done. I have basic knowledge with Picasso so will try that

AFAIK annotation processors just create code on build, the app will get bigger only if you create more and more custom loaders.

**Comment by 7LPdWcaW** [comment]
I think this ticket is now invalid. @EmmanuelMess can you try the latest version and see if the images feel like they load quicker? There were many improvements made in 2.6

**Comment by EmmanuelMess** [comment]
@7LPdWcaW I'll check once it uploads to FDroid.
