### ISSUE TITLE
add changelog

### ISSUE THREAD

**Issue by leela52452** [7LPdWcaW/GrowTracker-Android#121]
can you please add changelog.
what is [CHANGELOG](https://en.m.wikipedia.org/wiki/Changelog) ?

**Comment by 7LPdWcaW** [comment]
i'm not really sure this is needed as changelogs are provided for each release, also i've been adding changlog notes for f-droid [here](https://github.com/7LPdWcaW/GrowTracker-Android/tree/master/fastlane/metadata/android/en-GB/changelogs) unless this is specifically for some github feature?
