### ISSUE TITLE
Plant Life Cycle visualization in Statistics Screen

### ISSUE THREAD

**Issue by 9YbQiuEohUu1** [7LPdWcaW/GrowTracker-Android#123]
I love the fact that the app has all sorts of statistics and graphs. Wouldn't it be cool to have the information on the duration of plant's life cycles visualized in a chart?
![000](https://user-images.githubusercontent.com/50482952/64905369-f5b76a00-d6df-11e9-9aad-b98687138c21.PNG)

**Comment by 7LPdWcaW** [comment]
yes that's a great idea

**Comment by 9YbQiuEohUu1** [comment]
I just checked the graph in the alpha and it looks awesome! Noticed a couple of minor issues though:

1. To my understanding, the number of days is displayed to the right of its segment, which is confusing.

2. Looks like the name of the plant on the left just occupies valuable space. Since we're not dealing with side-by-side comparison of several plants, maybe it is not needed there?

3. Stage names are duplicated above and below the graph. 

4. Stages below the graph are not translated.

All things considered, maybe it would be better to 1) use just one list of stages which would specify both the colors and the number of days and 2) maybe organize the list vertically rather than in two rows for better clarity.
![crop](https://user-images.githubusercontent.com/50482952/65679088-1d51ef00-e05d-11e9-887b-29732ffd71f6.png)

**Comment by 7LPdWcaW** [comment]
I agree the graph labels are confusing, not sure how else i will be able to change them in the library being used, but i need to look at the colours anyway.

I'll remove plant name to make the graph wider, and the legend has to stay so you know what the colours match to. I'll add translations for them also.

Not sure I agree about removing the above fields, though, but i can see how its just duplicated data, although one is more visual than the other, having both isnt a bad thing

**Comment by 9YbQiuEohUu1** [comment]
> the legend has to stay so you know what the colours match to. I'll add translations for them also.
> 
> Not sure I agree about removing the above fields, though,

How about adding a colored rectangle to the stages in the upper field (or coloring the names themselves)? In any case, you are right-  duplicated data isn't that big of a deal.
