### ISSUE TITLE
Switching to MM/DD/YY format

### ISSUE THREAD

**Issue by 9YbQiuEohUu1** [7LPdWcaW/GrowTracker-Android#127]
The app has a very thoughtful selection of units settings. However, the dates can only be displayed in MM/DD/YY format with no possibility to choose DD/MM/YY instead. It would be great to have this option included. Thanks!

**Comment by 7LPdWcaW** [comment]
dates are formatted as per the device settings
![Screenshot_20190914-161951](https://user-images.githubusercontent.com/13586344/64910207-a9821f00-d70b-11e9-88dd-d0cea581a7b7.png)

**Comment by 9YbQiuEohUu1** [comment]
I didn't know that, thank you for clarifying. In this case there is certainly no need to add it as a setting.
