### ISSUE TITLE
garden backup not working in alpha, or is it ?

### ISSUE THREAD

**Issue by Maxtille** [7LPdWcaW/GrowTracker-Android#128]
I have backed up from stable release but when I try to restore from backup in alpha release it restores everything but garden. Though I still have the .json file related to garden from this date in the backup repository.
No urgence at all for me, I just wanted to notify :wink: :peace_symbol:

**Comment by Maxtille** [comment]
Oh :astonished: 
Just got back to the app and found my garden :smile:, therefore app had crashed probably in background mode. I have sent you the mail as proposed by my phone :wink:

**Comment by 7LPdWcaW** [comment]
hmm I dont see a crash mail, but I will try to reproduce anyway

**Comment by Maxtille** [comment]
Strange ... Do you want me to send you my crash logs ?

**Comment by 7LPdWcaW** [comment]
Just checked my emails and looks like I got it last night, thanks!

**Comment by 7LPdWcaW** [comment]
@Maxtille oh it looks like its crashing because of an action translation not matching to an enum. This will probably completely break your app, will make a fix as soon as I can

**Comment by 7LPdWcaW** [comment]
This has been fixed in the latest alpha https://github.com/7LPdWcaW/GrowTracker-Android/releases/tag/alpha
