### ISSUE TITLE
Some thoughts on Plant screen

### ISSUE THREAD

**Issue by 9YbQiuEohUu1** [7LPdWcaW/GrowTracker-Android#146]
Currently, the plant screen has this huge area in the middle with properties that are essentially fixed - so the user will only need to edit them once or maybe twice per plant's lifetime. On the other hand. As a result, some frequently used items (for adding waterings, actions, notes, and photos) are well within reach but a user needs to scroll down every time to view history, statistics, and photos (and, as far as I can tell, they are not accessible in any other way). Maybe it will be a good idea to reorganize this screen? Maybe hide the items from the highlighted area under the "advanced settings" tab or just moving the History, Statistics, and Photos buttons to the top, or create a "View Full History" button in the lower left corner of the last watering card, next to "Feed Again" (since it essentially represents the last history entry). 
![IMG_20190831_153434](https://user-images.githubusercontent.com/50482952/65894907-3c30e800-e3b3-11e9-9f2c-b612b39efb90.jpg)
![IMG_20190831_153852](https://user-images.githubusercontent.com/50482952/65894909-3cc97e80-e3b3-11e9-9ce1-e71ab7e1c363.jpg)

**Comment by 9YbQiuEohUu1** [comment]
Update: I have played with the latest alpha and it turns out there IS a way to access history, statistics, and photos through the Extreme card features, which is a very convenient addition (this is my preferred card style from now on). Nevertheless, I still think moving one-time options to the bottom may be a good idea.

**Comment by 7LPdWcaW** [comment]
you should check out the latest alpha https://github.com/7LPdWcaW/GrowTracker-Android/releases/tag/alpha

**Comment by 9YbQiuEohUu1** [comment]
The lower panel is BRILLIANT. Much better this way. Thanks.
