### ISSUE TITLE
Customizeable actions

### ISSUE THREAD

**Issue by Vexatos** [7LPdWcaW/GrowTracker-Android#149]
It would be very useful if you could define your own Actions from within the app. For instance, I was recently wanting one for trimming the grass around my plant and one for clearing dead branches.

**Comment by 7LPdWcaW** [comment]
I'd like to try and keep the list of actions as a set list as its being defined as a data structure. Happy to add more actions, but really for anything else you should just use the note action, for example, clearing dead branches would just be trimming, and then you could possibly also add that additional detail within the notes of the action.
