### ISSUE TITLE
Add option to change language/provide non-localised builds

### ISSUE THREAD

**Issue by Vexatos** [7LPdWcaW/GrowTracker-Android#150]
It would be nice if the upcoming version could have an option to change the language of the app, once translations are in.

**Comment by 7LPdWcaW** [comment]
I can not easily control the language of the app as it uses the system settings to determine which language set is used, what's the reason for this request?

**Comment by Vexatos** [comment]
My phone is in a different language than what I usually use while gardening, so it would be quite confusing to me.

**Comment by 7LPdWcaW** [comment]
From looking into it, it doesnt seem like there is a proper way to do this without using hacky code. I may instead just build an english only and a localised version of the app.

You could also look at apps that may allow you to control the language of an individual app? if you do find one that would be good.

**Comment by 7LPdWcaW** [comment]
[Latest APK (English only): (SHA256) 0f9cd87e57bcb9e402c9aeafba719a9f19be5c26fae54f756924da286403dcaa v2.6](https://github.com/7LPdWcaW/GrowTracker-Android/releases/download/v2.6/v2.6-en.apk)

**Comment by aha999** [comment]
Just adding to this... [Android 13 will enable changing each app's language](https://youtu.be/kR_DysDwk3k?t=154). but it would be nice if there was an option inside of Growtracker.

**Comment by 7LPdWcaW** [comment]
> Just adding to this... [Android 13 will enable changing each app's language](https://youtu.be/kR_DysDwk3k?t=154). but it would be nice if there was an option inside of Growtracker.

If Google are adding the ability to change an app's language on a per-app basis (like iOS does) then there wouldn't be a need to have a setting within the app itself

**Comment by aha999** [comment]
Regarding Android 13 yes, but currently 100% of devices aren't on Android 13 and most current devices will never recieve it. I think it would be a nice feature for any current device and for those that won't have android 13 (if it actually gets the feature)
