### ISSUE TITLE
Folder structure

### ISSUE THREAD

**Issue by 9YbQiuEohUu1** [7LPdWcaW/GrowTracker-Android#154]
Currently, the default folder structure is somewhat inconvenient. To back up all data, one needs to copy the "backups" folder, then go to DCIM to fetch the images. The latest alpha already has the option for changing the images location, which is great, but there is still no way of changing the backups location. In addition, I've noticed there's now a new GrowLogs folder in the root of the storage, which makes three separate locations for one app. I suggest to have a single GrowTracker folder in storage which would contain subfolders for Images, Backups, GrowLogs (whatever that is), and Crashes (which are currently in DCIM/GrowTracker for some reason). This would gather all data in one place, make backup and restore much easier, and reduce the cluttering of the storage.

**Comment by 7LPdWcaW** [comment]
Images will stay in the DCIM folder, backups will stay in the "backups" folder (as many apps use this folder and also I do no want to break backwards compatibility)/

I have moved crash logs and grow log exports into `Documents/GrowTracker/`

**Comment by 9YbQiuEohUu1** [comment]
Losing backward compatibility is a valid concern and something that I myself consider the main argument against changing the folder structure. However, it can be addressed via a single cut-paste operation once in a lifetime for each user. More importantly, it should not be the main criterion for deciding whether to address the issue. If there are advantages to it, we ought to think how to deal with backward compatibility. If there are no advantages, there is no reason to bother. I believe that having all app data in a better way to manage data, so I’ll try to explain my position as clearly as I can. I respect your vision of the way things should be but think that my perspective as an active user may also be helpful. 

It is true that many apps use certain paths (e.g., /backups) to store data. However, this is done mostly when the data is intended to be available to other apps. For example, messengers store images in their respective folders (e.g., Viber/Media/Viber Images, Whatsapp/Media/WhatsApp Images). These files are used internally (displayed in chat history). When a user wants to save the image for other purposes, then it is saved to a common folder (neither Viber nor WhatsApp does this but Telegram saves it to /Pictures). Signal does this in the best way possible: it stores images in an encrypted database and allows saving it to a common folder only after displaying an explicit warning:

![Screenshot_20191029-114442](https://user-images.githubusercontent.com/50482952/68497894-3eae1980-025e-11ea-801b-78c0eb184dce.jpg)


In the case of GrowTracker, the images are DEFINITELY not intended to be available to other parties. Hiding them with a .nomedia file is very thoughtful, but having them in plain sight in the most obvious location goes against the basic precautions of handling sensitive data. 

In addition, there is no uniform approach among developers regarding the location of backups. I remember having both the Backup and Backups folders in my device’s internal storage, with each used by one app. Still other apps store their backups in respective folders, such as Signal/Backups and WhatsApp/Backups. Currently, I have Documents and Backups folder which are used only by GrowTracker – two extra folders for one app. 
And every time I need to do a backup, I have to go to two locations to fetch the data, and I even cannot just select both and hit “copy” - I have to do one at a time to avoid copying the entire DCIM content. And as somebody who does it every time a new alpha is released, I can tell you – this is not fun at all :(

**Comment by 7LPdWcaW** [comment]
>In the case of GrowTracker, the images are DEFINITELY not intended to be available to other parties.

This is not true, the whole point of the app is that the data is accessible and open. The folders have a `.nomedia` file to prevent photos showing up in camera gallery. For proper security then you should be using the encryption mode which will encrypt all plant photos as well as the data. The location is not an issue for photos any more as you can set a custom location in 2.6.

I could possibly add a backup location path setting and then you could set them both to the same path, but wont be something Ill be working on soon.

You dont need to back up your photos for each alpha as the apps dont really deal with the photos once they are taken, the reason why I suggest to backup is because of the data.

**Comment by 9YbQiuEohUu1** [comment]
The reason I backup data every time I install a new alpha is because I’ve already lost some data due to encryption issues and do not want it to happen again. But suppose this is just an unnecessary precaution and I shouldn’t do that. Let’s consider a typical scenario where a user wants to backup all data and restore it on another device. In the current state, the necessary steps are:
1. Go to internal storage, fetch the backups folder, and put it somewhere (e.g., on a USB drive)
2. Return to internal storage again, go to DCIM folder, fetch the GrowTracker folder, and put it somewhere
3. Go to the new device’s internal storage, paste the backups folder;
4. Go to new device’s DCIM folder and paste the GrowTracker folder.
5. Go to the app and restore the backup.

In the case of a single folder, the necessary steps would be:
1. Go to internal storage, fetch the GrowTracker folder, and put it somewhere.
2. Go to new device’s internal storage and put the folder there. 
3. Go to the app and restore the backup.

The latter is clearly easier, more straightforward, and more intuitive. Also, it eliminates the possibility that during the migration, some folder is forgotten and lost (e.g., a user may not know that growlogs are stored in Documents and not back it up). 

Regarding the intention to make data accessible and open, I completely agree. In fact, I think that the way the app manages data is great. However, openness does not mean that all information should be available to everyone (otherwise the presence of encryption would violate it). It means that the user should have complete control over their data. From this perspective, storing everything in one folder would organize data in a more consistent and logical way, granting more control to its owner. This is also the approach used by many apps committed to the principles of freedom and privacy. 

That said, this is probably more than enough text to explain my opinion (I definitely didn’t plan to be that fixated on such a minor issue). I hope you’ll find this information useful and promise not to return to it again.
