### ISSUE TITLE
Add individual additive statistics and improve graph x-axis

### ISSUE THREAD

**Issue by 9YbQiuEohUu1** [7LPdWcaW/GrowTracker-Android#165]
It would be great to add some more simple stats to the Statistics tab, (I am particularly interested in Total Feedings and Average Time Between Feedings). It will be helpful for situations where you need to obtain a basic idea of each plant's conditions. 
It may also be necessary to separate the info on plant life cycle from the info on actions (maybe place the latter under the life cycle graph or just add another visual separator). 

Another possible improvement is the X axis in Feeding chart. Currently, it uses a legend based on separate stages (e.g. 3s, 6s, 2v, 6v, 1f, 5f etc.), so it's somewhat difficult to wrap one's head around it. Maybe the total day count would be more suitable? To visualize the relationship between feedings and plant stages, the chart's background could be colored using the watered down version of the life cycle color scheme or similar visual cues.

**Comment by 7LPdWcaW** [comment]
Im not sure I understand what it is you're requesting, the total water and ave. time between water stats already exist in the statistics tab.

I will need to see the capabilities of the graphing library to colour code sections of the graphs, but if it is possible, i will implement that. i'll also look at implementing a switch for the x-axis

**Comment by 9YbQiuEohUu1** [comment]
> Im not sure I understand what it is you're requesting, the total water and ave. time between water stats already exist in the statistics tab.

I mean feedings, not waterings, which will show how often the plant receives additives. Technically, this info can also be obtained from the first chart (as long as it has a uniform axis), but the mean value can still be useful - for example, to do a quick comparison of two plants.

**Comment by 7LPdWcaW** [comment]
It is possible to do. I originally had a distinction between "water" and "feed" but removed it because of complexity.

I can make it calculate if there are no additives vs if there are, but if you buffer your water with a non-nutrient or something than that will fall under as a "feed"

**Comment by 9YbQiuEohUu1** [comment]
What I'm after here is meaningful data on additives, which I think is at least as important as data on watering. Currently, if I want to find out how often was plant A fertilized compared to plant B, all I'm left with is looking at the dots on the Additives chart and trying to estimate the distance between them (you can tap the dots to see the precise date, but when you have entries like, say, 6s and 2v its not too helpful), or scroll through the History tab. This is why I feel that having total days would be more informative (maybe in the same format as photo's description #83  
Lifetime additive amount (in ml) is another simple metric that I think would be useful for similar purposes. Having both the total additives amount and the total number of feedings would help understanding fertilizing patterns (e.g. administering additives in smaller doses more frequently vs few large amounts).

**Comment by 7LPdWcaW** [comment]
- Pie chart of total nutrient distribution (or stacked bar chart)
- Total delivered nutrients over time (not concentration like current additive graph)

**Comment by 9YbQiuEohUu1** [comment]
>     * Total delivered nutrients over time (not concentration like current additive graph)

Another chart for total waterings, maybe? (not sure how useful it's going to be but it feels like a good thing to have)

Also, these stats:
Total Waters (already there)
Ave. Time Between Waters (already there)
**Lifetime Water Amount**

**Total Feedings** 
**Ave. Time Between Feedings**
**Lifetime Additive Amount**

Let's turn GrowTracker into a stats geek's paradise!
(in all seriousness, though, thank you for all the efforts, the app becomes more and more awesome with each release)

**Comment by 7LPdWcaW** [comment]
>Let's turn GrowTracker into a stats geek's paradise!

this was the idea, and why I wrote an open spec for the data structure!

**Comment by 7LPdWcaW** [comment]
@9YbQiuEohUu1 I have just made an alpha build with a re-write of the stats page that covers most if not all of this

https://github.com/7LPdWcaW/GrowTracker-Android/releases/tag/alpha

Left todo: implement these new stats for exports

**Comment by 9YbQiuEohUu1** [comment]
I have just checked the stats tab and it looks fantastic! I've spent a good part of the day checking old entries. :)
I have also already translated the new entries. Really informative and just interesting to check from time to time.

A couple of suggestions:
I would suggest changing "Total water used"  and "Total amount" to "Total water" and "Total additive" respectively or just Total amount for both for the sake of brevity and consistency. 
I'd also say Ave. **per** feeding sounds better than Ave. each feeding.

Thanks again!

**Comment by 9YbQiuEohUu1** [comment]
The latest alpha stopped showing graphs for additive concentration and additives over time.

**Comment by 9YbQiuEohUu1** [comment]
Another minor issue: "Total time" is calculated based on the current date instead of harvest date resulting in ridiculously long lifetimes.
(btw, should I create separate issues instead of reporting all stats-based problems here?)

**Comment by 7LPdWcaW** [comment]
@9YbQiuEohUu1 this should be fixed now. Separate issues for bugs is the best as I get a more prominent notification on github, plus means I dont need to re-close issues
