### ISSUE TITLE
(feature request) Tap an entry in the history tab to edit action

### ISSUE THREAD

**Issue by 9YbQiuEohUu1** [7LPdWcaW/GrowTracker-Android#170]
Editing is probably the most popular option in the action's drop-down menu (compared to duplicate, copy, and delete). I suggest it would be nice to enter the action editing mode simply by tapping it in the History tab. What do you think?

**Comment by 7LPdWcaW** [comment]
I avoided making those cards tappable specifically because it was too easy to accidentally tap them, especially as they have drag/drop functionality and other tappable elements (such as the menu icon)

**Comment by 9YbQiuEohUu1** [comment]
Hm. Sounds reasonable.
