### ISSUE TITLE
Display total amount of nutrients instead of concentration in the chart

### ISSUE THREAD

**Issue by 9YbQiuEohUu1** [7LPdWcaW/GrowTracker-Android#171]
(probably related to #165)
I've noticed that the value used in the Y axis of the Nutrients chart is concentration. Here's my issue with it: Let's say we give a plant 1 ml of a nutrient diluted in 500 ml. of water and another 1 ml diluted in 150 ml. the next day. In this case, the graph will show a huge spike despite the fact that the total amount of nutrients is the same. Conversely, if we water the plant with different amounts of the same solution (e.g. 500 with 5 ml. additive and 150 ml. with 1.5 ml. additive), the nutrient intake will be different but the graph will be flat. Wouldn't it be better to base the Y axis on the total amount of nutrients?

**Comment by 7LPdWcaW** [comment]
Yep the nutrient graph is concentration/ratio based (i.e how much measurement unit per delivery unit) as concentration is directly related to PPM/EC, this wont change.

There is space to add the total amounts, though, for example if I water 10L with 1.5ml/l of A then that would be 15ml of A in total. This could be plotted on a graph, along with a graph that shows distribution of total amounts over the life time. 

I will close this ticket and add this graph suggestion to #165

**Comment by 9YbQiuEohUu1** [comment]
> This could be plotted on a graph, along with a graph that shows distribution of total amounts over the life time.

This sounds like a good idea! My only concern is that plotting two sets of data on the same graph may make one of them illegible - for example, increasing the total amount from, say, 1.2 to 1.5 will barely register on a graph that has a Y axis of 5. In any case, I love the idea and can't wait to try it out.

**Comment by 7LPdWcaW** [comment]
Definitely as separate graphs, I think
