### ISSUE TITLE
Minor issue in Calendar

### ISSUE THREAD

**Issue by 9YbQiuEohUu1** [7LPdWcaW/GrowTracker-Android#172]
The dot that indicates an action in calendar is displayed with its lower part cut, especially in the horizontal layout. 
![sc](https://user-images.githubusercontent.com/50482952/69951784-9870cf00-14fe-11ea-9cae-c9e50071f64b.png)
![sc2](https://user-images.githubusercontent.com/50482952/69951794-9c045600-14fe-11ea-9bb0-ba8ff1c34db4.png)

**Comment by 9YbQiuEohUu1** [comment]
This issue is not resolved in 2.6.1. The dots are still displayed incorrectly both inportrait and landscape mode.

![Screenshot_20191219-100034](https://user-images.githubusercontent.com/50482952/71155773-23640000-2247-11ea-86af-5ff87ec5bee6.png)

![Screenshot_20191219-095551](https://user-images.githubusercontent.com/50482952/71155774-23640000-2247-11ea-89e5-859507a0b4ab.png)

What's more, if I try to switch from portrait to landscape when in calendar, it disappears completely. It can still be viewed when I enter the calendar from landscape-mode history.

![Screenshot_20191219-095600](https://user-images.githubusercontent.com/50482952/71155829-47274600-2247-11ea-84ce-1df95843cd2d.png)

**Comment by 7LPdWcaW** [comment]
The calendar being hidden is the temporary fix as it was completely blocking the scroll view in landscape and thus was useless (increasing the height would not fix this issue). Im going to look at re-doing this screen with a better calendar UI in the future
