### ISSUE TITLE
Adding a stage more than once messes up the day count and statistics

### ISSUE THREAD

**Issue by 9YbQiuEohUu1** [7LPdWcaW/GrowTracker-Android#181]
It looks like the app cannot handle a situation where a given stage (e.g. vegetation) is entered more than once throughout the plant's life cycle. For instance, when the plant starts blooming, I change it from Vegetation to Flowering and everything is fine:

![1](https://user-images.githubusercontent.com/50482952/71776702-cd10f400-2f9e-11ea-817f-2326b24118a9.png)
![2](https://user-images.githubusercontent.com/50482952/71776707-d4380200-2f9e-11ea-9c31-6949e93be78a.png)

At the end of the flowering phase, I change it back to Vegetation and this is what I get:

![3](https://user-images.githubusercontent.com/50482952/71776742-05b0cd80-2f9f-11ea-8cc8-0ad5b91c41a7.png)
![4](https://user-images.githubusercontent.com/50482952/71776743-05b0cd80-2f9f-11ea-911d-8452077b9d39.png)

It also messes up the counter in the plant's card (it now says "planted 5 months ago, -31 days vegetation).

Can something be done about it?

**Comment by 7LPdWcaW** [comment]
Im going to close this one as a wontfix for the current version of the app (as it was designed to be linear) and will ensure that it is correctly handled moving forward
