### ISSUE TITLE
Add a Custom medium option

### ISSUE THREAD

**Issue by aha999** [7LPdWcaW/GrowTracker-Android#182]
- You could add a custom medium "title" option for anyone that uses something else that is not listed or to quickly differentiate and identify by medium title if you're testing different mediums.

- That option would open a sub-window where you'd enter a medium title. 

- That medium would then save to saved mediums (unless manually removed)

**Comment by 7LPdWcaW** [comment]
I don't have any plans to add an option for custom mediums as its currently described in the dataspec as an Enum with set options.

Can you give some examples as to what additional mediums should be added that are not already available? I will expand the list, and possibly add an "other" option. The medium details field underneath should be used to describe complex recipes (such as soil + perlite and vermiculite)

AFAIK there isnt really a huge list of different medium types that people typically use

**Comment by aha999** [comment]
I agree with general/typical use and specific recipes can be written below.
