### ISSUE TITLE
Donations

### ISSUE THREAD

**Issue by aha999** [7LPdWcaW/GrowTracker-Android#184]
I think you (the developer) should open at least one platform for donations so anyone can voluntarily help fund this project.

Examples:
- [LiberaPay](https://liberapay.com/)
- [Github Sponsors](https://github.com/sponsors)
- [PayPal](https://www.paypal.com/)
- [Ko-fi](https://ko-fi.com/)
- [OpenCollective](https://opencollective.com/)

Displaying a sponsor button in your repository: [link](https://help.github.com/en/github/administering-a-repository/displaying-a-sponsor-button-in-your-repository)

**Comment by 7LPdWcaW** [comment]
I've written somewhere before about this, but basically I am unable to accept monetary donations at this time
