### ISSUE TITLE
Option to change app language

### ISSUE THREAD

**Issue by aha999** [7LPdWcaW/GrowTracker-Android#186]
It would be nice to have the option in the app to change the app-language to other languages without changing the system language. The reason would be, some people prefer english for these kinds of things because most forums, articles, plant growing techniques etc. are primarily in english language and it can be easier for some to use the app in english, and some words are basically untranslatable, like F**k i missed (FIM), Scrog, Lollipoping etc. with the sense of being understandable in the translated language what is it for.

There's probably more reasons why some could prefer english over their mother language (me included).

Please add an option in the settings to manually change between available languages.

**Comment by 7LPdWcaW** [comment]
Please see #150
