### ISSUE TITLE
UI tweak: Move "Stage Details" higher

### ISSUE THREAD

**Issue by 9YbQiuEohUu1** [7LPdWcaW/GrowTracker-Android#222]
Is it possible to change the position of the plant's stage? Unlike plant date and medium details, which are edited once or twice in the plant's life, its stage needs to be changed from time to time. On both my devices this section does not fit the screen and has to be scrolled down to. 

I would suggest placing it between name/strain and grow details. Alternatively, it can be included as a first option in the Grow Details group (above plant date). What do you think?

**Comment by 7LPdWcaW** [comment]
Yeah I totally agree

**Comment by 9YbQiuEohUu1** [comment]
It looks and works much better now, thanks.
BTW, what is the advantage of having separate fields for name/strain, stage, and the rest of the details? Plant date, for example, is related to medium details no more than to plant stage (maybe even less when you think about it). I'm not against sorting everything into categories - it just feels that in this case the division is somewhat arbitrary (and occupies extra space).

**Comment by 7LPdWcaW** [comment]
Was simply a design decision to break up content rather than just having a big list of fields. Also some containers are hidden depending on the state of the view (new plant vs existing plant)
