### ISSUE TITLE
Names of image folders

### ISSUE THREAD

**Issue by 9YbQiuEohUu1** [7LPdWcaW/GrowTracker-Android#229]
Folders that store images of each plant use a random string of characters as a name, which makes them really difficult to navigate and manage outside the app. Wouldn't it be better to use their creation date (YYYY-MM-DD-hh-mm-ss) as a name? It can be found out anyway from folder properties and files in it, so no sensitive info is given away.

**Comment by 7LPdWcaW** [comment]
I agree, however, this was originally the case (it used the plant name for folder name), but because plant name is editable (as is the plant date), it caused a lot more issues which is why i settled with ID. you can sort the folders by last modified. i would like to try and find a better in future

**Comment by 9YbQiuEohUu1** [comment]
I didn't mean the plant date (which can be edited and, what's worse, may be the same for several plants), but rather the entry creation date. Would be much more readable, informative, and would not rely on the functionality of a file manager.

**Comment by 9YbQiuEohUu1** [comment]
Okay, here's one way to solve this: why not use a YYYY-MM-DD-hh-mm-ss timestamp as an ID? This way the folders will have readable names and backward compatibility will not be broken. What do you think?
