### ISSUE TITLE
Images occasionally get broken from viewing?

### ISSUE THREAD

**Issue by 9YbQiuEohUu1** [7LPdWcaW/GrowTracker-Android#230]
Recently, while entering picture galleries of old entries, I've started noticing some of them are broken. I've checked the files from a file manager and it turns out all files in a given directory change their last modified date every time I view them. Apparently, that's when some of them get broken sometimes. I didn't modify these entries in any way - no fresh image uploads, no changes to the journal - just opened the app, swiped through the gallery, and closed it. The encryption is turned off.
Just installed the latest alpha and the behavior is still there (not sure if anything got broken this time).

**Comment by 7LPdWcaW** [comment]
Strange. I wonder if it's trying to write EXIF data for the comments and causing the file to be touched
