### ISSUE TITLE
[UI tweak] Move date above watering details in watering tab

### ISSUE THREAD

**Issue by 9YbQiuEohUu1** [7LPdWcaW/GrowTracker-Android#242]
Currently, the date is placed between water volume and additives, both of which are watering details. Can it be moved above to make the item placement more consistent and logical? Thanks.

**Comment by 9YbQiuEohUu1** [comment]
The date field doesn't separate volume and additives anymore. If there are no plans to move it to the top (which I feel would be a better place for it), the issue can be closed.

**Comment by 7LPdWcaW** [comment]
Date is a lesser field as it always defaults to "now" which is the intended use of the app. I'll close this for now, then.
