### ISSUE TITLE
Website for GrowTracker

### ISSUE THREAD

**Issue by aha999** [7LPdWcaW/GrowTracker-Android#245]
It would be nice to have a GrowTracker website so any articles in the future can link to it and the website would make a better visual representation of the project that could attract developers/contributors better.

A completely free and simple option is via Github Pages, that a lot of github open source projects are using, and you can even use/buy a custom domain like "[www.growtracker.app](https://instantdomainsearch.com/#search=growtracker)" if you want: https://pages.github.com/

    Hosted directly from your GitHub repository. Just edit, push, and your changes are live.
    No databases are needed to be set up and no servers to configure

Examples of repos that use github pages: https://github.com/collections/github-pages-examples

Interesting article: https://www.toptal.com/github/unlimited-scale-web-hosting-github-pages-cloudflare

    Consider Jekyll. You give it Liquid templates and Markdown content
    Free Jekyll templates: https://jekyllthemes.io/free

**Comment by 7LPdWcaW** [comment]
Ill consider making a landing/promo page using Github.io, but I won't be able to buy a domain or do anything that involves money.
