### ISSUE TITLE
Cant see photos

### ISSUE THREAD

**Issue by bellazinco** [7LPdWcaW/GrowTracker-Android#252]
Why?

**Comment by 7LPdWcaW** [comment]
Can you be more specific?

**Comment by bellazinco** [comment]
Sure! please find attached screenshots. Photos seem to be loaded but I cant open them

Inviato da ProtonMail mobile

-------- Messaggio originale --------
On 6 apr 2021, 20:49, 7LPdWcaW ha scritto:

**Comment by 7LPdWcaW** [comment]
Hi, there seems to be no screenshots.

Which part of the app are you seeing this? do you have encryption mode enabled? did you take the photos via the app, or import them via the gallery?

**Comment by bellazinco** [comment]
I just use the camera icon to upload images from gallery. There's no photo preview and when I try to open the image, it starts loading without showing it

Inviato da ProtonMail mobile

-------- Messaggio originale --------
On 7 apr 2021, 10:00, 7LPdWcaW ha scritto:

**Comment by 7LPdWcaW** [comment]
Hm, It is possible that the gallery app being used isnt transferring the photos into the app correctly. Could you try selecting a different app when choosing from the gallery?

Also which version of Android are you on? I think 10 and 11 have storage changes that might not work correctly

**Comment by bellazinco** [comment]
Hi dear,
I just tried taking photos directly via app and it seems working.
Ill keep you updated

Thanks a lot

Inviato da ProtonMail mobile

-------- Messaggio originale --------
On 7 apr 2021, 10:09, 7LPdWcaW ha scritto:

**Comment by 7LPdWcaW** [comment]
No problem! I suspect it is because of Android 10/11 which makes it a bit difficult to fix but I will see how much work is involved with it
