### ISSUE TITLE
Discussion group (live chat)

### ISSUE THREAD

**Issue by aha999** [7LPdWcaW/GrowTracker-Android#258]
I created a Telegram chat group for this project so users can chat in real time and discuss any questions / potential issues etc.

https://t.me/GrowTracker

If you @7LPdWcaW join it, i will give you ownership of the group, but if you dislike the idea i can delete the group.

**Comment by 7LPdWcaW** [comment]
You can be free to create one, but I will be unable to join or provide any app support except for issues raised here.
