### ISSUE TITLE
Plant database

### ISSUE THREAD

**Issue by garudaonekh** [7LPdWcaW/GrowTracker-Android#271]
Hi, it will be more helpful if plant database included. 
which should includes PH, moisture, light, nutrients,.. 

There is a freely available databases which included several thousands plants.

**Comment by 7LPdWcaW** [comment]
Hi, there are no plans to add a database of third party products or services to the app. You can configure the app with the nutrients you use via the "Feeding Schedule" section which gives quick access to pre-fill nutrient data when watering.
