### ISSUE TITLE
other languages

### ISSUE THREAD

**Issue by Maxtille** [7LPdWcaW/GrowTracker-Android#67]
would be so happy to have grow tracker available in french, but I'm sure other languages would be appreciated to

**Comment by 7LPdWcaW** [comment]
I will certainly extract out the strings into a language file to make it easier to translate, but i wouldnt be able to do the translations myself, so have to rely on the community for that

**Comment by Maxtille** [comment]
No problem, I can help with french ;)

**Comment by Maxtille** [comment]
Hey I just discovered transifex, you should check it out it's pretty usefull for translatting in comunity. 
I just would like to help the project but I still don't have enough android and java knowledge to achieve anything. so I'm waitting for what I'm able => translating to french :p

**Comment by 7LPdWcaW** [comment]
Translating the files will be easy, but first I need to extract the strings from code/layouts into a single file which is extremely boring and tedious so am currently doing it as and when I can :)

**Comment by EmmanuelMess** [comment]
I can do Spanish.

**Comment by EmmanuelMess** [comment]
What does "Light feeding with 2 week flush" mean?

**Comment by 7LPdWcaW** [comment]
Light feeding as in opposite of a "heavy feed" (say 1ml/l instead of 10ml/l) and 2 week flush means clearing out the nutrients with plain water for 2 weeks

**Comment by EmmanuelMess** [comment]
> Light feeding as in opposite of a "heavy feed" (say 1ml/l instead of 10ml/l) and 2 week flush means clearing out the nutrients with plain water for 2 weeks

I have no idea how to translate "flush" without it sounding like cleaning with bleach.

**Comment by 7LPdWcaW** [comment]
I would say use something to mean "to clear/wash out [of nutrients]"

**Comment by Noxmiles** [comment]
Hey, is there a possibility to translate now? I can help with german.

**Comment by 7LPdWcaW** [comment]
> Hey, is there a possibility to translate now? I can help with german.

The current working branch can be found at https://github.com/7LPdWcaW/GrowTracker-Android/tree/feature/resource-tidyups

am still in the process of extracting all the strings, but i'd say about 80% of them have been completed so far

**Comment by 7LPdWcaW** [comment]
To join as a translator, please sign up to transifex and I will add you as a contributor.

https://www.transifex.com/growutils/growtracker/dashboard/
