### ISSUE TITLE
Addition of 3 growth affecting prameters

### ISSUE THREAD

**Issue by peerzadaaabid** [7LPdWcaW/GrowTracker-Android#73]
Here I want to the suggestion that the following features should be added in he application in order to improve it.
1. Light
2.Temp
3.Nutrients

Thanks

**Comment by 7LPdWcaW** [comment]
Could you explain the fields and what you would want to record?

Temp is already a field available in watering, but this is more for the temp of the water

Nutrients (additives) are also available in watering

Im not planning on adding grow environment stats as it would require a drastic change to the structure of the app and data that's stored (its plant focused). There's no reason why you couldnt use the "note" feature to record arbitrary data in your environment
