### ISSUE TITLE
"Plant date" uses current date

### ISSUE THREAD

**Issue by 9YbQiuEohUu1** [7LPdWcaW/GrowTracker-Android#78]
When creating a new plant, the app ignores the entered date and instead uses the date when the entry is made. In the screenshot, the plant created on March 12 is displayed as planted on March 12 despite the entered plant date of January 27. The date can be changed in "Plant History" tab through "edit action" option. 
![Screenshot_20190327-224652_GrowTracker](https://user-images.githubusercontent.com/50482952/57517847-63ade800-7320-11e9-8999-f5a5ab4c6cb2.png)
![Screenshot_20190327-224728_GrowTracker](https://user-images.githubusercontent.com/50482952/57517848-63ade800-7320-11e9-9edd-6025c3f598cd.png)

**Comment by 7LPdWcaW** [comment]
This looks like an unintentional consequence of the change made a while back to add in plant stages as actions.

The plant date is actually a separate property to the "planted" action, although the "planted" action is added when the plant is created, it isnt actually tied to the plant date.

It would probably make sense to always use the "planted" action date for the "plant date", but then that might cause an issue if is deleted from the history.

I'll have a think about how to best solve this
