### ISSUE TITLE
Addition of root: shoot ratio and growth hormone features

### ISSUE THREAD

**Issue by peerzadaaabid** [7LPdWcaW/GrowTracker-Android#81]
After using the app and preparing a blog on utopian about this app, I found following features missing from the app,and I believe it will make the much better.
Root:shoot ratio
Growth hormones

**Comment by 7LPdWcaW** [comment]
Could you give me an example for "Growth hormones"? could this be just an additive for a watering? all fields are optional in the watering screen so you could add just the hormone as an additive.

For the root:shoot ratio, this is a descriptive property (unless im mistaken) so using a "Note action" would suit this.

Unless something is an "action" being applied to the plant (like trimming, or watering), it would fall under using a note action.

**Comment by peerzadaaabid** [comment]
Had the hormones being single, it would have been ok to add them in notes or in the watering screen. But here I wanna added all growth hormones including four major plant hormones like Auxins, ethylene, GA and cytokines
These hormones are usually given artificially either to increase growth or get a better yield of plants.

Will you allow me to prepare full descriptive details about the same?

Thanks

**Comment by 7LPdWcaW** [comment]
Could you give me a textual example of how you would typically log this?

for example: if I am spraying using a pre-made foliar feed product i would say

"I apply 5 sprays of FoliarProduct to the Stems"

something that will help me contextualise your requirements and think of a solution
