### ISSUE TITLE
Date of photos added from gallery

### ISSUE THREAD

**Issue by 9YbQiuEohUu1** [7LPdWcaW/GrowTracker-Android#82]
I really like how the app handles photos. However, adding a photo from gallery uses current time as a time the photo was taken, and I could not find a way to change the date afterwards in the “history” tab (as with actions). This can be misleading when adding images several days after they were taken. 

I think it would be great to have the possibility of changing the date while adding the photo (similarly to how it is done when adding a new action).

**Comment by 7LPdWcaW** [comment]
This is a good suggestion. I'll look at adding an option to use the original image's date/time. Although, the image may still be added to the bottom of the data array (i may have to add re-ordering functionality to the photo grid like with the actions list)

**Comment by 7LPdWcaW** [comment]
This is actually pretty complicated as I am unable to get the original file's date. One other way would be to give an option to edit the photo's date/time, but that wont solve the issue with the order of the photos which is driven by the stored data, not the file's date (as the file may not exist and the file name may not be a timestamp)

this is going to need much more consideration

**Comment by 9YbQiuEohUu1** [comment]
Actually, adding an option to edit the photo's date/time is a better solution than using the original file's date. This is what I meant by suggesting "the possibility of changing the date while adding the photo (similarly to how it is done when adding a new action)." 

As for the order of elements in the history tab, I have recently discovered that they can be dragged and dropped (I am now using it as a workaround for watering actions which, regardless of the set date always appear at the top of the list). However, unlike other elements, photos do not change their position no matter how long they are hovered over other elements. That is, they do not displace them and just return to their initial position once released.

**Comment by 7LPdWcaW** [comment]
Correct, this is because they are 2 different data sources combined together. Ordering photos in the history page doesnt make sense, it was originally just a list of actions, the ordering would have to be done in the photos page

**Comment by 9YbQiuEohUu1** [comment]
In any case, having photos in the history page is a really useful feature, and it would be great to have both full ordering functionality AND the possibility of setting and editing the date. Thank you for your efforts!

**Comment by 9YbQiuEohUu1** [comment]
So, it looks like late alphas use image properties to set the date in a diary, which is really handy. However, it seems like the app uses the "last modified" date for this. This means that cropping a photo or even moving it between devices sets off the date. Shouldn't image creation date be used instead?

**Comment by 7LPdWcaW** [comment]
I dont think there's a way to get the original creation date. Will mark this as wontfix. I hope the future functionality will address this issue
