### ISSUE TITLE
Feature request: Display age/stage of plant under photo

### ISSUE THREAD

**Issue by 9YbQiuEohUu1** [7LPdWcaW/GrowTracker-Android#83]
Currently, viewing a photo in fullscreen shows the date when the photo was taken (or, to be more precise, the date when it was added to the album). It would be great to also have the plant’s age displayed somewhere below (in the same way it is currently displayed in the “History” tab (e.g. “45 d / 15 flowering”). This would be helpful to see how a given plant looked at a certain age without additional calculations or external apps.

**Comment by 7LPdWcaW** [comment]
I've attempted to do this a couple of times but something always blocked me. I will take another attempt

**Comment by 9YbQiuEohUu1** [comment]
Thanks a lot for adding the stage counter! Could you also add the display of the plant's total age?  So, for example, instead of [ 6f ] it would say [ 48d / 6f ]? 

Here is why it would be great: one could see how does a plant of a certain strain should look at a given age. Having only the stage is only partially helpful because stage onset can vary from plant to plant, which can be misleading.

The app already displays the age in this way near each photo in the History tab, which is very convenient. It would be great to have the same functionality for photo viewing mode - both under fullscreen photos and next to previews in the View Photos tab. 

Thanks again!
