### ISSUE TITLE
Missing plant stage

### ISSUE THREAD

**Issue by 9YbQiuEohUu1** [7LPdWcaW/GrowTracker-Android#84]
There is no "seedling" stage in the app. In the literature, it is often placed between germination and vegetation. In the app, there is a "cutting" stage between them in the dropdown menu, which I assume to occur between flowering and drying. Now, I do not know if the order of options in the menu matters at all, but all other stages are arranged chronologically. In any case, are there plans to add the seedling stage or was it left out on purpose?

**Comment by 7LPdWcaW** [comment]
>Now, I do not know if the order of options in the menu matters at all, but all other stages are arranged chronologically. 

What do you mean by this? as far as im aware, any time the stage list is displayed it should be in the order defined in the enum which is date order (i.e planted -> germination/cutting -> vegetation -> flower, etc)

**Comment by 9YbQiuEohUu1** [comment]
You are correct, it does show up in this exact order. I just didn't know "cutting" was a stage between germination and vegetation. I seem to be unfamiliar with this term since this stage is mor commonly referred to as "seedling" (or I am missing something).

**Comment by 7LPdWcaW** [comment]
I see, no this is just an option that would typically replace germination as germination is a seed specific stage, not necessarily the next stage from the previous in the list. The example I gave above is the typical order (now with the addition of seedling which would be included in the germination/cutting grouping)
